version: "3.8"

services:
  app:
    build: ./
    ports:
      - "80:3000"
    init: true # See https://mzqvis6akmakplpmcjx3.hatenablog.com/entry/2020/11/10/231047
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

volumes:
  es-data:
    driver: local
